version: "3"
services:
#  jdk:
#    image: openjdk
#    container_name: jdk
#    volumes:
#      - ".:/app"
#    working_dir: "/app"

#  build:
#    image: maven
#    container_name: builder
#    volumes:
#      - ".:/usr/src/mymaven"
#      - "./etc/maven:/root/.m2"
#    working_dir: "/usr/src/mymaven"
#    entrypoint: "mvn verify"